### ISSUE TITLE
I can't init glfw:X Error of failed request:  BadRRCrtc (invalid Crtc parameter)

### ISSUE THREAD

**Issue by touching-foots-huskie** [glfw/glfw#1040]
I can't init the glfw:
when I am using glfw.init()
it comes out:
'''
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  22 (RRGetCrtcGammaSize)
  Crtc id in failed request: 0xeb
  Serial number of failed request:  61
  Current serial number in output stream:  61
'''
when I check xrandr:
it comes out that there is no monitor
So what should I do?

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by touching-foots-huskie** [comment]
I install it by  pip install glfw. and I am using python3.5. I am not sure about the version.

**Comment by elmindreda** [comment]
What does `glfwGetVersionString` return?

**Comment by touching-foots-huskie** [comment]
What do you mean by glfwGetVersionString? it is not a bash command or a python command? How I use it?

**Comment by elmindreda** [comment]
It's a GLFW function.

I don't know what they named that function in your Python binding, but it should be in there if it's a complete binding.

**Comment by elmindreda** [comment]
The reason I'm asking is that it sounds like one of several bugs that were fixed a while ago.

**Comment by touching-foots-huskie** [comment]
I believe it is glfw 3? Because I notice it is calling this "/usr/lib/x86_64-linux-gnu/libglfw.so.3.0'"
And on the python website: "https://pypi.python.org/pypi/glfw/1.4.0 " it is saying it is wrapper for glfw3

**Comment by touching-foots-huskie** [comment]
(3, 0, 4) , it is the output of glfw.get_version()

**Comment by elmindreda** [comment]
Thank you. That looks very plausible.

That version of GLFW was released in 2013 and many bugs have been fixed since, most likely including this one. Try upgrading to a newer version.

**Comment by touching-foots-huskie** [comment]
Oh, that's really good. ehhhh, but I still have a problem. 
I have used "git clone, cmake, cmake make make install" 
I only got a libglfw3.a, but I think I may need a .so file for the python interface. So may you tell me which part of your cmakelist should I change?

**Comment by touching-foots-huskie** [comment]
well~, I think my situation is getting more complicated.  When I am testing the test file in glfw/test.
I got "Segmentation fault (core dumped)" for every test program.
The glfwinfo runs out:
"GLFW header version: 3.3.0
GLFW library version: 3.3.0
GLFW library version string: "3.3.0 X11 GLX EGL clock_gettime /dev/js"
Segmentation fault (core dumped)
"
So what the probelm might be???

**Comment by elmindreda** [comment]
> I only got a libglfw3.a, but I think I may need a .so file for the python interface. So may you tell me which part of your cmakelist should I change?

You don't need to change that file. Run `cmake -DBUILD_SHARED_LIBS=1 .` instead of `cmake .` to [build the shared library](http://www.glfw.org/docs/latest/compile_guide.html#compile_options).

> So what the probelm might be???

I can't tell without more information. Try running it in a debugger (gdb or lldb) and see where the crash occurs.

**Comment by elmindreda** [comment]
```sh
cmake -DCMAKE_BUILD_TYPE=Debug .
gdb tests/glfwinfo
run
bt
```

**Comment by touching-foots-huskie** [comment]
The compile option is very useful, so the first problem is solved. I ran the glfw in a debug mode as your instruction.
And here is the output:
`(ENV3.5) exx@exx:~/glfw$ gdb tests/glfwinfo
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tests/glfwinfo...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/exx/glfw/tests/glfwinfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
GLFW header version: 3.3.0
GLFW library version: 3.3.0
GLFW library version string: "3.3.0 X11 GLX EGL clock_gettime /dev/js shared"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bab80d in chooseGLXFBConfig () from /home/exx/glfw/src/libglfw.so.3
(gdb) bt
#0  0x00007ffff7bab80d in chooseGLXFBConfig () from /home/exx/glfw/src/libglfw.so.3
#1  0x00007ffff7bad035 in _glfwChooseVisualGLX () from /home/exx/glfw/src/libglfw.so.3
#2  0x00007ffff7ba896d in _glfwPlatformCreateWindow () from /home/exx/glfw/src/libglfw.so.3
#3  0x00007ffff7b9edc2 in glfwCreateWindow () from /home/exx/glfw/src/libglfw.so.3
#4  0x000000000040bcc9 in main ()
(gdb)`

**Comment by touching-foots-huskie** [comment]
So what the problem might be?

**Comment by elmindreda** [comment]
Sorry, don't know yet. You did everything perfectly but I forgot a step (so we didn't get frame information or line numbers).
```
cmake -DCMAKE_BUILD_TYPE=Debug .
make clean all
gdb tests/glfwinfo
run
bt
```

**Comment by touching-foots-huskie** [comment]
Ok, that's fine. Is it enough for this time?
'''
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tests/glfwinfo...done.
(gdb) run
Starting program: /home/exx/glfw/tests/glfwinfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
GLFW header version: 3.3.0
GLFW library version: 3.3.0
GLFW library version string: "3.3.0 X11 GLX EGL clock_gettime /dev/js shared"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bab80d in chooseGLXFBConfig (desired=0x7fffffffd4e0, result=0x7fffffffd3d0)
    at /home/exx/glfw/src/glx_context.c:78
78              const GLXFBConfig n = nativeConfigs[i];
(gdb) bt
#0  0x00007ffff7bab80d in chooseGLXFBConfig (desired=0x7fffffffd4e0, result=0x7fffffffd3d0)
    at /home/exx/glfw/src/glx_context.c:78
#1  0x00007ffff7bad035 in _glfwChooseVisualGLX (ctxconfig=0x7fffffffd460, fbconfig=0x7fffffffd4e0,
    visual=0x7fffffffd418, depth=0x7fffffffd414) at /home/exx/glfw/src/glx_context.c:630
#2  0x00007ffff7ba896d in _glfwPlatformCreateWindow (window=0x637640, wndconfig=0x7fffffffd4a0,
    ctxconfig=0x7fffffffd460, fbconfig=0x7fffffffd4e0) at /home/exx/glfw/src/x11_window.c:1709
#3  0x00007ffff7b9edc2 in glfwCreateWindow (width=200, height=200, title=0x4113b7 "Version", monitor=0x0,
    share=0x0) at /home/exx/glfw/src/window.c:200
#4  0x000000000040bcc9 in main (argc=1, argv=0x7fffffffde58) at /home/exx/glfw/tests/glfwinfo.c:628
'''

**Comment by elmindreda** [comment]
That's perfect. Thank you!

...I have no idea how that would fail, though. Looking into it.

**Comment by touching-foots-huskie** [comment]
That will be helpful. I have been in trouble with it for a while.

**Comment by elmindreda** [comment]
If you change line 67 of `src/glx_context.c` from
```c
    if (!nativeCount)
```
to
```c
    if (!nativeConfigs || !nativeCount)
```
does that affect anything?

**Comment by touching-foots-huskie** [comment]
The error changes into:
`(gdb) run
Starting program: /home/exx/glfw/tests/glfwinfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
GLFW header version: 3.3.0
GLFW library version: 3.3.0
GLFW library version string: "3.3.0 X11 GLX EGL clock_gettime /dev/js shared"
Error: GLX: No GLXFBConfigs returned
Error: GLX: Failed to find a suitable GLXFBConfig
[Inferior 1 (process 2865) exited with code 01]
(gdb) bt
No stack.
(gdb)
`

**Comment by elmindreda** [comment]
So the good news is we found an easily fixed bug in GLFW. The bad news is your machine appears not to have OpenGL support.

**Comment by touching-foots-huskie** [comment]
hhh, finding the problem is also good for me.  so may you tell me what should I do?

**Comment by elmindreda** [comment]
At this point a Ubuntu users forum would probably be better equipped to help you. It's very unusual for an Ubuntu system to not even have fallback software OpenGL.

**Comment by touching-foots-huskie** [comment]
Thank you very much for your help!

**Comment by elmindreda** [comment]
@touching-foots-huskie Thank you for finding a bug! Sorry it didn't get you all the way and hope you things working soon!
