### ISSUE TITLE
Window title is lost when toggling from windowed to fullscreen and back

### ISSUE THREAD

**Issue by jhauberg** [glfw/glfw#1082]
OS: **MacOS 10.13 High Sierra**
GLFW Version: **GLFW 3.3.0 Cocoa NSGL** @ 32e78ae

You can see this happening in the example `boing`.

1) Run the `boing` test app, verify that the window title is `Boing (classic Amiga demo)`
2) Press <kbd>alt-enter</kbd> to trigger fullscreen
3) Press <kbd>alt-enter</kbd> again to exit fullscreen
4) Window title is lost

In my own app I was just going to implement a quick fix by grabbing the current title before going fullscreen and setting it back when exiting, but then noticed that there wasn't a counterpart for getting the title as there is for setting it; i.e. there is a `glfwSetWindowTitle`, but there's not a `glfwGetWindowTitle` (which may be a separate issue in its own).

**Comment by elmindreda** [comment]
This should be fixed now with 5aeb37d1b89a566d70c86c72aec1f11ce5b15c3e. Thank you for reporting this!

**Comment by jhauberg** [comment]
This issue is still in effect in latest `master` https://github.com/glfw/glfw/commit/0be4f3f75aebd9d24583ee86590a38e741db0904.

If the window is initially created as fullscreen, the title is lost when switching to windowed (it does work the other way around though).

I modified the `boing` example to reproduce the issue:

```diff
index 45c867fd..507f3b5f 100644
--- a/examples/boing.c
+++ b/examples/boing.c
@@ -89,7 +89,7 @@ typedef enum { DRAW_BALL, DRAW_BALL_SHADOW } DRAW_BALL_ENUM;
 typedef struct {float x; float y; float z;} vertex_t;

 /* Global vars */
-int windowed_xpos, windowed_ypos, windowed_width, windowed_height;
+int windowed_xpos, windowed_ypos, windowed_width = 400, windowed_height = 400;
 int width, height;
 GLfloat deg_rot_y       = 0.f;
 GLfloat deg_rot_y_inc   = 2.f;
@@ -627,7 +627,15 @@ int main( void )
    if( !glfwInit() )
       exit( EXIT_FAILURE );

-   window = glfwCreateWindow( 400, 400, "Boing (classic Amiga demo)", NULL, NULL );
+    GLFWmonitor * const monitor = glfwGetPrimaryMonitor();
+    GLFWvidmode const * const mode = glfwGetVideoMode(monitor);
+
+    window = glfwCreateWindow(mode->width,
+                              mode->height,
+                              "Boing (classic Amiga demo)",
+                              monitor,
+                              NULL);
+
    if (!window)
    {
        glfwTerminate();
```

To reproduce, run through same steps as mentioned originally.
