### ISSUE TITLE
Wrong frame buffer size under GNOME/Wayland in a high resolution screen

### ISSUE THREAD

**Issue by AlynxZhou** [glfw/glfw#1168]
Hello everyone, I am using a 3840x2160 screen with GNOME/Wayland, and I am learning OpenGL ES with glfw-wayland under Arch Linux. I have a problem that the frame buffer size seem wrong, because GNOME has a scale factor in my screen, I create a window which has a size of 1920x1080 it will be fullscreen, and then I get the frame buffer size, create the gl viewport with the size, and then draw triangles in normal, but GLES only draws in the lower-left part, I have tried glfw-x11 under wayland using xwayland, and it works fine, also in other window size x11 fine but wayland always wrong. So maybe glfw needs care about desktop's scala factor? Or if developers think that's not what glfw controls, could anyone tells me how to solve it? Thanks.

Here is my screenshot under wayland:

![screenshot from 2018-01-04 19-59-26](https://user-images.githubusercontent.com/8444615/34563404-77da4af0-f18d-11e7-9ba1-36796d06d3a6.png)

and here is my code(a little bit long but it works):

```
#define GLFW_INCLUDE_ES3
#include <stdio.h>
#include <stdlib.h>
#include <GLFW/glfw3.h>
#include <GLES3/gl3.h>
#include "svpng.inc"
#include "loaders/shader_loader.h"
#include "loaders/program_loader.h"
#include "loaders/png_loader.h"

static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
	if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
		glfwSetWindowShouldClose(window, GLFW_TRUE);
}

int main(int argc, char *argv[])
{
	glfwInit();
	// glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	// glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	// glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_RESIZABLE, GL_TRUE);
	GLFWwindow *window = glfwCreateWindow(1920, 1080, "My Title", NULL, NULL);
	if (!window)
		return EXIT_FAILURE;
	int width, height;
	glfwGetFramebufferSize(window, &width, &height);
	glViewport(0, 0, width, height);
	glfwSetKeyCallback(window, key_callback);
	glfwMakeContextCurrent(window);
	GLfloat vertices[] = {
		-0.5f, -0.5f, 0.0f,	1.0f, 0.0f, 0.0f,	//0.0f, 0.0f,
		0.5f, -0.5f, 0.0f,	0.0f, 1.0f, 0.0f,	//1.0f, 0.0f,
		0.0f, 0.5f, 0.0f,	0.0f, 0.0f, 1.0f,	//0.5f, 0.5f
	};
	GLuint vao;
	glGenVertexArrays(1, &vao);
	glBindVertexArray(vao);
	GLuint vbo;
	glGenBuffers(1, &vbo);
	glBindBuffer(GL_ARRAY_BUFFER, vbo);
	glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);
	GLuint program = load_program("v.glsl", "f.glsl");
	// GLuint texture = load_png_texture("sister.png");
	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), (GLvoid *)0);
	glEnableVertexAttribArray(0);
	glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), (GLvoid *)(3* sizeof(GLfloat)));
	glEnableVertexAttribArray(1);
	// glVertexAttribPointer(2, 2, GL_FLOAT,GL_FALSE, 8 * sizeof(GLfloat), (GLvoid *)(6 * sizeof(GLfloat)));
	// glEnableVertexAttribArray(2);
	glBindVertexArray(0);
	while (!glfwWindowShouldClose(window)) {
		glfwPollEvents();
		glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
		glClear(GL_COLOR_BUFFER_BIT);
		glUseProgram(program);
		// glBindTexture(GL_TEXTURE_2D, texture);
		glBindVertexArray(vao);
		glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_INT, 0);
		glBindVertexArray(0);
		glBindVertexArray(vao);
		glDrawArrays(GL_TRIANGLES, 0, 3);
		glBindVertexArray(0);
		// glBindTexture(GL_TEXTURE_2D, 0);
		glfwSwapBuffers(window);
	}
	// free_png_texture(texture);
	free_program(program);
	glfwTerminate();
	return 0;
}
```

If you think my loaders and shaders is needed I can upload it, but I am afraid they have nothing because they are simple loaders and shaders.

**Comment by linkmauve** [comment]
Note that you aren’t asking for a fullscreen window, in order to do that you have to pass a `GLFWmonitor` to `glfwCreateWindow()`.

I will install GNOME and investigate, thanks for your report.

**Comment by AlynxZhou** [comment]
@linkmauve Yes, I just not testing fullscreen window, what I mean is that it deals with scale factor correctly in X11 but wrong in wayland, so when you create a window and get size from glfw then pass it to gl viewport, gl will only draw in 1/4 of the window, that's wrong. Thank you for your test.

**Comment by ruuda** [comment]
I am experiencing the same issue. `glfwGetFramebufferSize` and `glfwGetWindowSize` return the same values, even though I have a high-dpi display with scaling factor 2. I have only a single display, and I am using GNOME 3.28 under Wayland.

**Comment by rmasp98** [comment]
I can confirm this affects me too! It only seems to affect me when I have scaling on (for 4k). It also only started to affect me when I ran an update which upgrade both mesa (18.1.5-1 -> 18.1.6-1) and xorg-server-xwayland (1.20.0-9 -> 1.20.1-1)

Let me know if any more information would be helpful!

Disro = Arch Linux
GLFW = glfw-wayland 3.2.1-1
Desktop = gnome 3.28
Harware = Razer Blade stealth - 4k screen 
resolution = 3840x2160 (200% scaling)

**Comment by linkmauve** [comment]
Please test on master (glfw-git in AUR, install only the glfw-wayland-git package generated), this should have been fixed for a very long time already.

**Comment by AlynxZhou** [comment]
Oh I forget it until today...with glfw 3.3-2, this problem still exists, seems glfw create window in double size.

**Comment by AlynxZhou** [comment]
OK, I am doing more tests for this problem and find some funny things:

I am using a 3840x2160 screen with 200% scale factor, and if I start a window whose size is 1920x1080 with `glfw-wayland`, **the window looks really like 3840x2160**, it takes the full screen:

![Screenshot from 2019-11-10 00-17-20](https://user-images.githubusercontent.com/8444615/68531690-025ae600-0350-11ea-8498-c514b90be13c.png)

but it's interesting that `glfwGetWindowContentScale` gives us `1.0`:

![Screenshot from 2019-11-10 00-22-21](https://user-images.githubusercontent.com/8444615/68531706-3209ee00-0350-11ea-8262-e16bd9404e6e.png)

the scale is correct, because the triangle size is correct for 1920x1080, but window size is incorrect...it scaled itself.

And with `glfw-x11`, window size and content size is both correct as 1920x1080:

![Screenshot from 2019-11-10 00-17-20](https://user-images.githubusercontent.com/8444615/68531723-71383f00-0350-11ea-8f15-a117ca6becf0.png)

but don't be happy! Look the bottom of the termianl, **`glfwGetWindowContentScale` returns `2.0`**! The window is clearly not scale, it is 1920x1080, why we have scale in 2.0?

In case anyone needs my code, you can download them here:
- <https://sh.alynx.moe/posts/Learn-OpenGL-1/main.c>
- <https://sh.alynx.moe/posts/Learn-OpenGL-1/triangle.f.glsl>
- <https://sh.alynx.moe/posts/Learn-OpenGL-1/triangle.v.glsl>

**Comment by DevSrSouza** [comment]
Yeh, I had the same weird result of `scale 2.0` while using on X11 with Fractional Scalling on Ubuntu. The monitor does not have any scalling but it show as 2.0

**Comment by felix-u** [comment]
I don't mean to pry, but are there any updates on this? I know there must be few glfw users on Wayland (for now, anyway), but it would be a fantastic QoL improvement for those of us who use fractional scaling to be able to run glfw windows natively rather than through XWayland.

**Comment by manio** [comment]
Hi,
I only want to make sure if I understand the current situation properly. Currently I am using `glfw-wayland` under Arch.
In SwayWM I have scaling set to 2 on my 4K display. When I start the application on this screen it is blurry/ugly scaled.

So currently the scaling with wayland and [wp-fractional-scale-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143) is not supported, right?

**Comment by MarcDoughty** [comment]
I am a GLFW user on Wayland (Minecraft set to use a self-compiled GLFW library so I can force native Wayland), on Ubuntu 23.10, using GNOME.

I can confirm that GLFW at the time of this writing is not leveraging the recent Wayland Fractional Scaling protocol. If you set your fractional scale to a non-integer (mine is at 125%), the game will render a much larger virtual screen (slow because it uses too much GPU) and the compositor downscales it (also slow, and a bit ugly).

If I apply this patch to GLFW I get a fast and beautiful Wayland game session with 1:1 pixel rendering:

https://github.com/DanShaders/minecraft-wayland/blob/one-nineteen/0008-Wayland-Add-support-for-wp_fractional_scale_v1.patch

Please consider that Wayland is now the default display technology on leading distros, and that the opportunity to get this awesome feature into into the next Long Term Support release of Ubuntu closes in February 2024.

**Comment by elmindreda** [comment]
Support for fractional-scale-v1 has now been added with 2b3f919b6055e6837ca0fad193c7f96b323f1256. Framebuffer scaling can now be disabled via the `GLFW_SCALE_FRAMEBUFFER` window hint with a9cc7c7260c32068a5374ce9d59515df540de970.
