### ISSUE TITLE
glfwPollEvents aborts program (BadWindow/X_TranslateCoords)

### ISSUE THREAD

**Issue by lodi** [glfw/glfw#1633]
Release 3.3.1 throws the following error from `glfwPollEvents()` on my wayland+sway system:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x0
  Serial number of failed request:  132
  Current serial number in output stream:  132
```

I've narrowed down the problem to commit fe57e3c (2020-01-01).  The previous commit, 6b01aff (2020-01-01), works fine.  Both commits work okay under gnome3 though.

I read [somewhere](https://www.gitmemory.com/issue/glfw/glfw/1620/572231113) that this problem might be related to running a tiling window manager with no window decorations, but I tested both with and without window decorations and in my case fe57e3c doesn't work either way.  

Here's my test code:

```c
#include <stdio.h>
#include <GLFW/glfw3.h>

void quit(GLFWwindow *window, int key, int scancode, int action, int mods)
{
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
        glfwSetWindowShouldClose(window, GLFW_TRUE);
    }
}

void error_callback(int code, const char* description)
{
    printf("error: %s\n", description);
}

int main()
{
    glfwInit();

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    GLFWwindow *window = glfwCreateWindow(1280, 720, "GLFW OpenGL", NULL, NULL);
    glfwMakeContextCurrent(window);

    glfwSetErrorCallback(error_callback);
    glfwSetKeyCallback(window, quit);

    while (!glfwWindowShouldClose(window)) {
	
	printf("polling events...\n");

        glfwPollEvents();

	printf("polled events\n");

        glfwSwapBuffers(window);
    }

    glfwDestroyWindow(window);
    glfwTerminate();
}
```

Note that `error_callback` isn't invoked, and `glfwPollEvent()` doesn't return; the program just aborts. 

```
os: NixOS, kernel 4.19.98, sway 1.4
```

**Comment by mmilata** [comment]
Am also getting this on xmonad (i.e. tiling wm w/o decorations).
```
os: NixOS, kernel 5.4.15, xmonad 0.15, xorg 1.20.5, amdgpu driver
```

**Comment by elmindreda** [comment]
Thank you for reporting this. It was fixed with 9372ba95faabd1bb45280d201d6ccdae77bf872e in #1620, which was included in the recent 3.3.2 release.

**Comment by lodi** [comment]
Thanks @elmindreda.  I can confirm that 9372ba9 works for me.

**Comment by seichter** [comment]
I'm on Arch Linux with X11 - using 3.3.2 and still have the same issue - same error with `glfwPollEvents()`. Any hint how to debug that it seems to crash deep inside of X11?

**Comment by elmindreda** [comment]
@seichter Have you checked the version string in case it's an older binary interfering somewhere?

**Comment by seichter** [comment]
Yes. It's same and I made sure its not interfering with the system installed GLFW. Basically I am rewriting one of my old 3D engines and use GLFW as input and window handler. Source in in-tree for the code, the library is built as subproject with CMake and linked statically. If I leave out `glfwPollEvents()` things work but obviously I have no input handling and the like.

**Comment by elmindreda** [comment]
@seichter I cannot reproduce this with 3.3.2. What window related hints do you set? Does the bundled GLFW test `windows` have the same issue on your machine?

**Comment by seichter** [comment]
I drilled it down to [this line](https://github.com/glfw/glfw/blob/0ac013381be83fcd6e53ea874f09b1895943bd9e/src/x11_window.c#L1561) but couldn't figure out what might caused it.

**Comment by elmindreda** [comment]
@seichter What window manager are you using?

It could happen if the window was reparented and the parent window destroyed before GLFW processed the configure event. I'll add an Xlib error handler grab around using the cached parent handle.

**Comment by seichter** [comment]
I'm on ArchLinux with latest Gnome/Mutter in a gnome-session - the problem appeared already with the old 3.34.x series. Both machines are using the proprietary NVidia driver (if enabled). One machine is using a patched gdm from AUR for optimus-manager and is usually running with the Intel driver - problem persists independently of driver.

```
$ pacman -Q mutter gnome-session gnome-shell
mutter 3.36.0-1
gnome-session 3.36.0-1
gnome-shell 1:3.36.0-3
```

**Comment by elmindreda** [comment]
@seichter Does this happen when you poll right after window creation or when you do something with the window via input or code or something else?

**Comment by seichter** [comment]
@elmindreda I was just digging a bit deeper in my code. The engine code was after window initialization and setting up callbacks hiding the window (with glfwHideWindow) and shortly before starting the update loop showing it again (with glfwShowWindow). If I disable this, the update loop works as expected. In glfw 3.2.1 there was no problem here.

**Comment by elmindreda** [comment]
@seichter Oh, that makes perfect sense. Thank you!

**Comment by elmindreda** [comment]
This should be fixed now with e65de2941c056ee5833b4dab3db36b297b53aa14. Thank you @lodi and @mmilata for reporting it and @seichter for all the patient debugging help.
