### ISSUE TITLE
glfwTerminate throws 0x80010012 exception on Windows

### ISSUE THREAD

**Issue by TurtleMan64** [glfw/glfw#2659]
In the following simple glfw program, the final `glfwTerminate` is throwing a `0x80010012` exception.

```
#include <GLFW/glfw3.h>
#include <stdio.h>

int main(int argc, char* argv[])
{
    if (!glfwInit())
    {
        printf("glfwInit failed\n");
        return -1;
    }

    GLFWwindow* window = glfwCreateWindow(640, 480, "GLFW Test", nullptr, nullptr);
    if (!window)
    {
        printf("glfwCreateWindow failed\n");
        glfwTerminate();
        return -1;
    }
    
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);
    
    while (!glfwWindowShouldClose(window))
    {
        glClear(GL_COLOR_BUFFER_BIT);
        glfwSwapBuffers(window);
        glfwPollEvents();
    }
    
    glfwDestroyWindow(window);
    glfwTerminate(); //throws exception

    return 0;
}
```

`Exception thrown at 0x00007FF8DFFCFA4C (KernelBase.dll) in GLFW_Test.exe: 0x80010012: The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call did not execute.`

This is with GLFW 3.4, Visual Studio 2022, Windows 11.

I have also tried compiling the latest GLFW code from source and using that, but it still has the same exception.

According to the stack trace in Visual Studio, it appears to be the `DestroyWindow(_glfw.win32.helperWindowHandle)` call in the `_glfwTerminateWin32` function:
![pic2](https://github.com/user-attachments/assets/dfb23701-f224-4bc0-bcf4-2191eab3474f)

The exception only seems to happen if a window is created.

The program still exits with return code 0. But the exception is worrisome.

**Comment by dougbinks** [comment]
I've not seen this before, and use GLFW 3.4 with Visual Studio 2022 on Windows 11 daily. The exception is also a bit odd, though it could be a generic COM message about some handle already being invalidated.

However this is somewhat suspicious and I'm wondering if you have a program (or virus/worm) installed which hooks into your program. Though unlikely, I've seen [weird issues before with plugins like Nahimic](https://github.com/ocornut/imgui/issues/45420), so it's worth checking. You can see the modules your program has loaded at runtime by pausing execution and looking at the debug > modules window and sorting by path to find non-windows modules.

**Comment by TurtleMan64** [comment]
Thanks for looking into this. I checked the modules loaded for my test program, all 68 of them were located in System32 (other than the executable itself).

I'm not sure how to check that Nahimic issue since the link seems to be a 404, but I'm assuming that there would be some other dll loaded not from System32?

In my case I don't have Nahimic, but I do have Realtek HD Audio Universal Service which might be a similar type of software. But there didnt seem to be any Realtek dlls loaded that I could see.

**Comment by GamesTrap** [comment]
> 
> Though unlikely, I've seen [weird issues before with plugins like Nahimic](https://github.com/ocornut/imgui/issues/45420), so it's worth checking.

Probably meant this issue:

- https://github.com/ocornut/imgui/issues/4542

**Comment by dougbinks** [comment]
Thanks @GamesTrap I've fixed the extra 0 on the link.

@TurtleMan64 if all the other modules are in your System32 folder then this doesn't look like a DLL injection issue.

I would next check updating your drivers, and turning off any AMD/NVIDIA/Intel game HUD options if you have any on.

**Comment by TurtleMan64** [comment]
I am using a GeForce RTX 3060, and updated my drivers to the latest available (566.36). Even after doing this and restarting, still encounter the exception.

As for HUD options, I don't think I have anything like that enabled. I don't have GeForce Experience or MSI Afterburner/RTSS. If there is an overlay then it's something I'm unaware of going on in the background. But I'm not sure how to check for that.

**Comment by dougbinks** [comment]
This is still somewhat puzzling.

What happens if you run any of the GLFW tests or examples in the source distribution (or from Github), or this GLFW-CMake-starter https://github.com/enkisoftware/GLFW-CMake-starter?

**Comment by TurtleMan64** [comment]
I followed the readme for the GLFW-CMake-starter and ran its example program, and glfwTerminate threw the same exception after I closed the window.

I also tried out the "boing" example from the glfw source on github. Program runs fine, but also throws the same exception when I close the window.

**Comment by dougbinks** [comment]
Thanks!

I still cannot replicate this and I can't see any logic wrong with the way GLFW creates and destroys the helper window. I am not very familiar with the error, but I think it would normally occur if a COM object was being used which no longer existed. The fact this is occurring on a `CharUpperW` call is also a bit weird.

I'm about 90% sure that there's something odd with your system, as I can't replicate this and we've had no other similar reports. At this point I'm a bit out of ideas as to what to investigate, but I would run a virus scan just in case.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
just to be sure it is not VS being nasty here (yes i have had issues with VS where binary it produces have weird issues), perhaps you can compile an example from glfw using a different compiler.

[glfw34_gears.zip](https://github.com/user-attachments/files/18401782/glfw34_gears.zip)
if you dont have access to another compiler, you can use provided gears example.

if the provided sample fails with same error, i would try to fix COM interfaces using some special tools (they modify registry so make sure to backup first), or possibly delete dead/offending COM interfaces entries from registry. (again backup first)
