### ISSUE TITLE
Full screen + Command Tab causes crash

### ISSUE THREAD

**Issue by MasonRemaley** [glfw/glfw#503]
I was getting a crash when command tabbing in and out of my full screen application, so to figure out what was going on I wrote a small test program that just creates a full screen window and keeps it open.

When I run this code on OSX 10.10.3 and command tab out and then back in, it crashes on the call to glfwPollEvents. This seems like a bug to me, I think whatever was at 0x608000060000 before I command tabbed in and out is no longer there or something. Below is the test program and the console output after the crash. Let me know if I'm missing something or if you need any more info on my end to figure this out.

<pre>
int main()
{
    glfwInit();
    GLFWwindow* window = glfwCreateWindow(512, 512, "Window", glfwGetPrimaryMonitor(), nullptr);
    glfwMakeContextCurrent(window);
    
    while (!glfwWindowShouldClose(window))
    {
        glfwPollEvents();
    }
}
</pre>

<pre>
2015-04-23 01:28:24.670 Demo[12201:1127695] -[__NSMallocBlock__ frame]: unrecognized selector sent to instance 0x608000060000
2015-04-23 01:28:24.671 Demo[12201:1127695] An uncaught exception was raised
2015-04-23 01:28:24.671 Demo[12201:1127695] -[__NSMallocBlock__ frame]: unrecognized selector sent to instance 0x608000060000
2015-04-23 01:28:24.671 Demo[12201:1127695] (
    0   CoreFoundation                      0x00007fff84e7003c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff92b8f76e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff84e730ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00007fff84db8e24 ___forwarding___ + 1028
    4   CoreFoundation                      0x00007fff84e716c8 __forwarding_prep_1___ + 120
    5   Demo                                0x000000010002aa16 enterFullscreenMode + 79
    6   Demo                                0x000000010002a97c -[GLFWWindowDelegate windowDidBecomeKey:] + 33
    7   CoreFoundation                      0x00007fff84e2c45c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    8   CoreFoundation                      0x00007fff84d1c634 _CFXNotificationPost + 3140
    9   Foundation                          0x00007fff889c79d1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    10  AppKit                              0x00007fff89de5bd9 -[NSWindow becomeKeyWindow] + 1406
    11  AppKit                              0x00007fff89ffbdda _NXShowKeyAndMain + 186
    12  AppKit                              0x00007fff89e15a01 -[NSApplication sendEvent:] + 8375
    13  Demo                                0x000000010002b9af -[GLFWApplication sendEvent:] + 146
    14  Demo                                0x000000010002c908 _glfwPlatformPollEvents + 67
    15  Demo                                0x0000000100001e6d main + 109
    16  libdyld.dylib                       0x00007fff83b115c9 start + 1
)
2015-04-23 01:28:24.876 Demo[12201:1127695] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSMallocBlock__ frame]: unrecognized selector sent to instance 0x608000060000'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff84e7003c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff92b8f76e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff84e730ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00007fff84db8e24 ___forwarding___ + 1028
    4   CoreFoundation                      0x00007fff84e716c8 __forwarding_prep_1___ + 120
    5   Demo                                0x000000010002aa16 enterFullscreenMode + 79
    6   Demo                                0x000000010002a97c -[GLFWWindowDelegate windowDidBecomeKey:] + 33
    7   CoreFoundation                      0x00007fff84e2c45c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    8   CoreFoundation                      0x00007fff84d1c634 _CFXNotificationPost + 3140
    9   Foundation                          0x00007fff889c79d1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    10  AppKit                              0x00007fff89de5bd9 -[NSWindow becomeKeyWindow] + 1406
    11  AppKit                              0x00007fff89ffbdda _NXShowKeyAndMain + 186
    12  AppKit                              0x00007fff89e15a01 -[NSApplication sendEvent:] + 8375
    13  Demo                                0x000000010002b9af -[GLFWApplication sendEvent:] + 146
    14  Demo                                0x000000010002c908 _glfwPlatformPollEvents + 67
    15  Demo                                0x0000000100001e6d main + 109
    16  libdyld.dylib                       0x00007fff83b115c9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
</pre>

**Comment by jaredjones** [comment]
I am unable to replicate this.

**Comment by elmindreda** [comment]
I am also unable to reproduce this.

**Comment by MasonRemaley** [comment]
I tried it again just now and realized that my demo is a little deceptive. GLFW first creates the window, and then takes a moment to finish loading. Sometimes the loading only takes a moment, but the first few times I run an app using GLFW it takes a good 3-5 seconds. It's easy to inadvertently switch focus after the window is created but before it finishes loading since my demo doesn't draw anything. If I do this, I don't get a crash. However, if I wait until it finishes loading, I get a crash every time.

If you guys still can't recreate this let me know and I'll mess with it some more/see if I can find another computer to try it out on.

**Comment by MasonRemaley** [comment]
Here's the updated code I'm running right now for your convenience. It changes the background color to red so you can tell when it's finished loading, and it doesn't change your resolution so that it doesn't mess up all your windows every time you run it:

<pre>
#include <GLFW/glfw3.h>
#include <OpenGL/gl.h>

int main()
{
	glfwInit();
	
	GLFWmonitor* monitor = glfwGetPrimaryMonitor();
	const GLFWvidmode* mode = glfwGetVideoMode(monitor);
	
	glfwWindowHint(GLFW_RED_BITS, mode->redBits);
	glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
	glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
	glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
	
	
	GLFWwindow* window = glfwCreateWindow(mode->width, mode->height, "My Title", monitor, nullptr);
	
	glfwMakeContextCurrent(window);
	glClearColor(1.0, 0.0, 0.0, 1.0);
	
	while (!glfwWindowShouldClose(window))
	{
		glfwPollEvents();
		glClear(GL_COLOR_BUFFER_BIT);
		glfwSwapBuffers(window);
	}
}
</pre>

**Comment by jaredjones** [comment]
Sorry man but I still can't get your program to crash. Oh and btw you shouldn't include <OpenGL/GL.h>. Let GLFW do this for you.

**Comment by MasonRemaley** [comment]
Thanks, got rid of the OpenGL include. Are you also running OSX 10.10.3?

**Comment by jaredjones** [comment]
Here's my machine's specs... Have you tried deleting your derived data yet?

![screen shot 2015-05-13 at 7 23 32 pm copy](https://cloud.githubusercontent.com/assets/1316894/7623859/a5a73d68-f9a5-11e4-8259-94f4c84845ac.png)

**Comment by MasonRemaley** [comment]
Just did Product->Clean and deleted the derived data, it still crashes. I've attached a picture of my specs as well. When 10.11 is released (I assume you're running a beta or something?) I'll update and see if I still get the crash. Meanwhile I'll mess around some more and see if I can find another computer to try and recreate this on.
![screen shot 2015-05-13 at 8 37 15 pm](https://cloud.githubusercontent.com/assets/5516083/7624041/a85e8dee-f9b0-11e4-8259-b49e1231ebce.png)

**Comment by jaredjones** [comment]
Yea I had to remove the picture because I don't think the buddy who gave it to me from Apple would be happy if I left it up.
Anyhow, I also tried this on OS X 10.10.4 (14E17e) and it's working for me as well.

What version of Xcode are you running out of curiosity?

**Comment by jaredjones** [comment]
@MasonRemaley Upload the compiled executable along with the xcodeproject; provide a link here and I'll see if I can replicate it with that binary.

**Comment by MasonRemaley** [comment]
Sorry for the late response--I've been in exams all week. I'm running Xcode Version 6.3.1 (6D1002).

I've uploaded my Xcode project + an executable. I copied my installation of GLFW into the project folder and setup the project to use that in case that's where the problem is. When I run the executable directly (rather than running it through Xcode), it gets the spinning beachball for a while before it crashes.

https://www.dropbox.com/s/ert2w1xonfakh0r/GLFW%20Crash.zip?dl=0
(It'll ask you to make a DropBox if you don't have one, you can just close that dialog and it'll still let you download the file. Let me know if you have any issues.)

**Comment by jaredjones** [comment]
So I ran both executables and they both ran perfectly on my machine with "Tabbing". I also built the project from source and I had no issues with it as well.

Strange.

**Comment by MasonRemaley** [comment]
Hm, that's weird. A friend offered to let me try to reproduce this on their computer, it might be a couple of days from now but when I get a chance I'll try it out and let you know what happens.

**Comment by MasonRemaley** [comment]
I finally got a chance to try it out on my friend's computer and I couldn't get it to crash. Furthermore, I made a new account on my computer and it didn't crash there either. It also didn't pause during start up in either place like it does on my account. On my account, it has taken on a new pattern of alternating between running correctly and then crashing every other time I open it.

I have no idea how, but it seems like it's just an issue with my account and I'll have to reinstall--thank you guys for helping trying to figure this one out! Let me know if you think there's anything more to this, but otherwise feel free to close the issue.

**Comment by jaredjones** [comment]
Great news! Sorry about your account though, I really wish I knew what could be causing it. You're able to close this issue yourself since you were the creator.

**Comment by MasonRemaley** [comment]
I'd been considering reinstalling anyway for other reasons, so it's not too bad--at least I know how to get things working now!

**Comment by MasonRemaley** [comment]
I went ahead and backed up my files, wiped my computer, reinstalled OS X, and copied the project (as well as some other files) onto my new account. This solved numerous other problems with my computer, and got rid of the strange pause when starting up an application using GLFW, but it still crashes.

Surprised, I made a second admin account to see if it would behave any differently there. On the alternative account, it crashes--but only when Xcode is open. I'm not running it through Xcode, but somehow Xcode being open in the background causes it to crash. When I close Xcode, it starts working normally again. On my main account, it crashes every other time I try it regardless of Xcode being open.

I have no idea what this could mean, any thoughts?

**Comment by nachtsky** [comment]
I had the same issue and cannot figure out what happened either. Did you know how to solve this?

**Comment by MasonRemaley** [comment]
Unfortunately no, I was never able to solve this issue on my computer or recreate it on anyone else's. What are your computer's specs?

**Comment by jnsmalm** [comment]
I'm also having the exact same problem (running OS X 10.10.3). I'm not using Xcode, I use CLion. For me it doesn't matter if CLion is running in the background or not. It crashes when alt+tabbing back to a fullscreen application. Get the following stack:

2015-07-18 22:36:54.306 jsplay[3916:158307] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PAPerfLoggingIntervalTransitionEvent frame]: unrecognized selector sent to instance 0x7fd8b840c960'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff897e903c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8695776e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff897ec0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff89731e24 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff897ea6c8 __forwarding_prep_1___ + 120
	5   jsplay                              0x0000000102f3f774 enterFullscreenMode + 116
	6   jsplay                              0x0000000102f3f675 -[GLFWWindowDelegate windowDidBecomeKey:] + 69
	7   CoreFoundation                      0x00007fff897a545c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	8   CoreFoundation                      0x00007fff89695634 _CFXNotificationPost + 3140
	9   Foundation                          0x00007fff872ce9d1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	10  AppKit                              0x00007fff8dca0bd9 -[NSWindow becomeKeyWindow] + 1406
	11  AppKit                              0x00007fff8deb6dda _NXShowKeyAndMain + 186
	12  AppKit                              0x00007fff8dcd0a01 -[NSApplication sendEvent:] + 8375
	13  jsplay                              0x0000000102f410ea -[GLFWApplication sendEvent:] + 170
	14  jsplay                              0x0000000102f421c7 _glfwPlatformPollEvents + 135
	15  jsplay                              0x0000000102f3d96e glfwPollEvents + 46
	16  jsplay                              0x000000010278ace1 _ZN6Window10PollEventsEv + 17
	17  jsplay                              0x000000010278b53b _ZN6Window10PollEventsERKN2v820FunctionCallbackInfoINS0_5ValueEEE + 155
	18  ???                                 0x00000eece0e36f64 0x0 + 16410548072292
	19  ???                                 0x00000eece0e375ac 0x0 + 16410548073900
	20  ???                                 0x00000eece0e2effd 0x0 + 16410548039677
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by elmindreda** [comment]
A number of bugs related to full screen windows on macOS have been fixed recently. The fixes are available in the master branch.

**Comment by jnsmalm** [comment]
Thanks! This helped for the fullscreen problem my application had.

**Comment by MasonRemaley** [comment]
Hm I replaced my version of the library with the one in master and unfortunately I still get the crash. I didn't get it at first, but then I remembered that back when I first opened this issue I was building with Xcode--and so I switched from building with `g++` to building with Xcode and got a similar crash again upon command tabbing back in:

```
2017-04-27 01:20:57.942343 GLFW Crash[34267:1267456] -[_CFXNotificationObserverRegistration frame]: unrecognized selector sent to instance 0x608000064480
2017-04-27 01:20:57.943958 GLFW Crash[34267:1267456] [General] An uncaught exception was raised

2017-04-27 01:20:57.943988 GLFW Crash[34267:1267456] [General] -[_CFXNotificationObserverRegistration frame]: unrecognized selector sent to instance 0x608000064480
2017-04-27 01:20:57.944384 GLFW Crash[34267:1267456] [General] (
	0   CoreFoundation                      0x00007fff7cabe6fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff912c5a2a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7cb3ecc4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff7ca31f03 ___forwarding___ + 1059
	4   CoreFoundation                      0x00007fff7cad3458 __forwarding_prep_1___ + 120
	5   GLFW Crash                          0x00000001000053a6 enterFullscreenMode + 79
	6   GLFW Crash                          0x000000010000530c -[GLFWWindowDelegate windowDidBecomeKey:] + 33
	7   CoreFoundation                      0x00007fff7ca4b5ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	8   CoreFoundation                      0x00007fff7ca4b4eb _CFXRegistrationPost + 427
	9   CoreFoundation                      0x00007fff7ca4b252 ___CFXNotificationPost_block_invoke + 50
	10  CoreFoundation                      0x00007fff7ca09972 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
	11  CoreFoundation                      0x00007fff7ca0895b _CFXNotificationPost + 667
	12  Foundation                          0x00007fff7e4360e3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	13  AppKit                              0x00007fff7a7ec19c -[NSWindow becomeKeyWindow] + 1445
	14  AppKit                              0x00007fff7a7ebbb5 _NXSendWindowNotification + 248
	15  AppKit                              0x00007fff7a9b78fc _NXShowKeyAndMain + 145
	16  AppKit                              0x00007fff7aae70f9 -[NSApplication _handleActivatedEvent:] + 1387
	17  AppKit                              0x00007fff7adcfb53 -[NSApplication(NSEvent) sendEvent:] + 2815
	18  GLFW Crash                          0x000000010000633f -[GLFWApplication sendEvent:] + 146
	19  GLFW Crash                          0x00000001000072a5 _glfwPlatformPollEvents + 67
	20  GLFW Crash                          0x00000001000010d9 main + 281
	21  libdyld.dylib                       0x00007fff91ba2255 start + 1
)
2017-04-27 01:20:57.988544 GLFW Crash[34267:1267456] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_CFXNotificationObserverRegistration frame]: unrecognized selector sent to instance 0x608000064480'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7cabe6fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff912c5a2a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7cb3ecc4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff7ca31f03 ___forwarding___ + 1059
	4   CoreFoundation                      0x00007fff7cad3458 __forwarding_prep_1___ + 120
	5   GLFW Crash                          0x00000001000053a6 enterFullscreenMode + 79
	6   GLFW Crash                          0x000000010000530c -[GLFWWindowDelegate windowDidBecomeKey:] + 33
	7   CoreFoundation                      0x00007fff7ca4b5ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	8   CoreFoundation                      0x00007fff7ca4b4eb _CFXRegistrationPost + 427
	9   CoreFoundation                      0x00007fff7ca4b252 ___CFXNotificationPost_block_invoke + 50
	10  CoreFoundation                      0x00007fff7ca09972 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
	11  CoreFoundation                      0x00007fff7ca0895b _CFXNotificationPost + 667
	12  Foundation                          0x00007fff7e4360e3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	13  AppKit                              0x00007fff7a7ec19c -[NSWindow becomeKeyWindow] + 1445
	14  AppKit                              0x00007fff7a7ebbb5 _NXSendWindowNotification + 248
	15  AppKit                              0x00007fff7a9b78fc _NXShowKeyAndMain + 145
	16  AppKit                              0x00007fff7aae70f9 -[NSApplication _handleActivatedEvent:] + 1387
	17  AppKit                              0x00007fff7adcfb53 -[NSApplication(NSEvent) sendEvent:] + 2815
	18  GLFW Crash                          0x000000010000633f -[GLFWApplication sendEvent:] + 146
	19  GLFW Crash                          0x00000001000072a5 _glfwPlatformPollEvents + 67
	20  GLFW Crash                          0x00000001000010d9 main + 281
	21  libdyld.dylib                       0x00007fff91ba2255 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by elmindreda** [comment]
@MasonRemaley Thank you for testing again! I see `enterFullscreenMode` in your call stack, though, which was removed in GLFW 3.2. You may be linking against the wrong file.

**Comment by MasonRemaley** [comment]
Ha yup, you're right. :) I'm actually not sure how this happened though. I uninstalled the version I got through Homebrew and recompiled which as expected caused a linker error confirming that's the version it was using. Then I installed from source:

```
$ git clone -b latest https://github.com/glfw/glfw/
$ cd glfw
$ mkdir build
$ cd build
$ cmake ..
$ make install
```

After doing this the build succeeds again, but `glfwGetVersion` still returns `v3.1.1`. I'm probably doing something silly but I have no idea what it could be. I'll try to mess with it some more tomorrow, but let me know if you see anything wrong with those steps.

**Comment by tombsar** [comment]
Can this issue be closed?

**Comment by MasonRemaley** [comment]
Your call--I never successfully confirmed whether or not the issue was fixed.

**Comment by elmindreda** [comment]
Closing this for now. Please bump or reopen at any time if there is more information.
