### ISSUE TITLE
Add option to avoid _glfwPlatformPollEvents in glfwInit

### ISSUE THREAD

**Issue by stbrowne** [glfw/glfw#886]
It looks like the call to _glfwPlatformPollEvents was added with the helper window in commit 4cd493dd9a461e9c06f9cae1ac27d015d38a71f7.

I would like an option to avoid this call (or if it's not necessary remove it without an option). In my specific scenario I already have a GUI toolkit that has it's own Windows message loop. I'm simply using glfw for offscreen OpenGL for video post processing. The post processing effect is an optional piece of our software which is why I don't want to just call glfwInit on startup which would eliminate the problem. 

The problem with _glfwPlatformPollEvents being called in glfwInit is that we may end up calling this while we have multiple video streams being received and displayed. While all of this is going on if there is heavy enough load then the Windows message queue may never be emptied and therefor glfwInit will never actually return until all of the messages are processed. I'd really rather there not be a message loop inside glfwInit, but if there must be it would be nice if it exited after it got the particular message it's looking for. In my case I don't see it ever doing anything in windowProc other than going to DefWindowProcW so I don't even think the poll is necessary at all, but I could be wrong.

**Comment by elmindreda** [comment]
This was fixed with 7420814fe20346d8e8b074ede9d77bc5546bb5fe, but I forgot to tag it.

**Comment by nidefawl** [comment]
This still isn't fixed.
_glfw.win32.helperWindowHandle will be NULL until createHelperWindow() returns.
So its passing a NULL handle to PeekMessageW and still processing foreign windows messages.

**Comment by elmindreda** [comment]
@nidefawl You are absolutely correct.

**Comment by elmindreda** [comment]
@nidefawl This has (hopefully) been fixed with 5292914ce19ed2dc6c6abfd591c4df18820a466a.
