### ISSUE TITLE
first responder error on window creation (since macOS Sierra)

### ISSUE THREAD

**Issue by MyForteIsTimeTravel** [glfw/glfw#908]
2016-11-29 12:03:03.040681 Tribes[12757:699578] [General] ERROR: Setting <GLFWContentView: 0x101422470> as the first responder for window <GLFWWindow: 0x10400ec10>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fffa58f29a4 -[NSWindow _validateFirstResponder:] + 566
	1   AppKit                              0x00007fffa50e39eb -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fffa518b66a -[NSWindow _realMakeFirstResponder:] + 406
	3   AppKit                              0x00007fffa518b480 -[NSWindow makeFirstResponder:] + 123
	4   Tribes                              0x000000010003392e createNativeWindow + 1230
	5   Tribes                              0x000000010003320f _glfwPlatformCreateWindow + 63
	6   Tribes                              0x000000010003d947 glfwCreateWindow + 887
	7   Tribes                              0x000000010000cee0 _ZN4Game8initGLFWEv + 192
	8   Tribes                              0x000000010000ccc1 _ZN4GameC2Ev + 129
	9   Tribes                              0x000000010000cfd5 _ZN4GameC1Ev + 21
	10  Tribes                              0x0000000100015226 main + 38
	11  libdyld.dylib                       0x00007fffbc514255 start + 1
	12  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by elmindreda** [comment]
This should be fixed with #883.

**Comment by MyForteIsTimeTravel** [comment]
Built from master just now, still throws the exact same error.

**Comment by jhauberg** [comment]
I experience the same issue. MacOS Sierra 10.12.1.

**Comment by elmindreda** [comment]
@MyForteIsTimeTravel What does `glfwGetVersionString` return?

**Comment by MyForteIsTimeTravel** [comment]
"Version: 3.2.1 Cocoa NSGL chdir menubar retina"

As Jhauberg says it isn't a crash error or anything, but it does throw this error consistently on 10.12.

**Comment by elmindreda** [comment]
@MyForteIsTimeTravel The version in master is 3.3, so you are linking against an older version.

**Comment by MyForteIsTimeTravel** [comment]
Okay, i must have copied the wrong one after i built. Sorry, my bad!

**Comment by elmindreda** [comment]
@MyForteIsTimeTravel No worries! Happens to us all. Does the library built from master work better?

**Comment by MyForteIsTimeTravel** [comment]
Yeah it does, i got 3.3.0 and the errors gone. Many thanks

**Comment by elmindreda** [comment]
@kesperado What does `glfwGetVersionString` return?
